-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2025-10-13T01:45:29.454Z

CREATE TYPE "estado_usr" AS ENUM (
  'activo',
  'suspendido',
  'eliminado'
);

CREATE TYPE "estado_pbcn" AS ENUM (
  'Activo',
  'Cancelado',
  'Completado'
);

CREATE TYPE "tipo_pago" AS ENUM (
  'tarjeta',
  'cupon'
);

CREATE TYPE "estado_intc" AS ENUM (
  'en_proceso',
  'cancelado',
  'completado'
);

CREATE TYPE "unidades" AS ENUM (
  'kilogramos',
  'litros',
  'electricidad'
);

CREATE TYPE "tipo_campana" AS ENUM (
  'Reciclaje',
  'Donacion',
  'Reparacion'
);

CREATE TABLE "Rol" (
  "id_rol" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre_rol" varchar NOT NULL,
  "descripcion" text
);

CREATE TABLE "Usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "correo" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "contrasena" varchar NOT NULL,
  "estado" estado_usr NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "Bitacora_Usuario" (
  "id_bitacora" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "accion_realizada" varchar NOT NULL,
  "fecha_accion" timestamp NOT NULL,
  "detalle" text NOT NULL,
  "usuario_id" int NOT NULL
);

CREATE TABLE "Billetera" (
  "id_billetera" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "credito_total" money NOT NULL DEFAULT 0,
  "credito_actual" money NOT NULL DEFAULT 0,
  "credito_retenido" money NOT NULL DEFAULT 0,
  "ultima_actualizacion" timestamp DEFAULT (NOW()),
  "usuario_id" int NOT NULL
);

CREATE TABLE "Movimiento_Credito" (
  "id_mov_credito" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tipo_movimiento" varchar NOT NULL,
  "monto" money NOT NULL,
  "origen" varchar NOT NULL,
  "fecha_mov" timestamp NOT NULL,
  "descripcion" text NOT NULL,
  "billetera_id" int NOT NULL
);

CREATE TABLE "Billetera_Puntos" (
  "id_billetera_Puntos" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "total" int NOT NULL,
  "en_posesion" int NOT NULL,
  "ultima_actualizacion" timestamp DEFAULT (NOW()),
  "usuario_id" int NOT NULL
);

CREATE TABLE "Publicacion" (
  "id_publicacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "titulo" varchar NOT NULL,
  "precio" money NOT NULL,
  "campo" text NOT NULL,
  "existencias" int NOT NULL,
  "peso_unidad" decimal NOT NULL,
  "foto" text,
  "descripcion" text,
  "estado" estado_pbcn,
  "fecha_publicacion" timestamp DEFAULT (NOW()),
  "usuario_id" int NOT NULL,
  "categoria_id" int NOT NULL
);

CREATE TABLE "Favorito" (
  "usuario_id" int NOT NULL,
  "publicacion_id" int NOT NULL,
  "fecha_marcado" timestamp DEFAULT (NOW())
);

CREATE TABLE "Categoria" (
  "id_categoria" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "descripcion" text
);

CREATE TABLE "Paquete_Recarga" (
  "id_paquete" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre_paquete" varchar NOT NULL,
  "puntos" int NOT NULL,
  "costo" money NOT NULL,
  "fecha_actualizado" timestamp DEFAULT (NOW())
);

CREATE TABLE "Compra_Paquete" (
  "id_compra" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "metodo_pago" tipo_pago NOT NULL,
  "fecha_compra" timestamp DEFAULT (NOW()),
  "billetera_puntos_id" int NOT NULL,
  "paquete_recarga_id" int NOT NULL
);

CREATE TABLE "Canjeo_Puntos" (
  "billetera_id" int NOT NULL,
  "billetera_puntos_id" int NOT NULL,
  "cantidad" int NOT NULL,
  "fecha_canje" timestamp DEFAULT (NOW())
);

CREATE TABLE "Intercambio" (
  "id_intercambio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "creditos_verdes" money NOT NULL,
  "cantidad" int NOT NULL,
  "estado" estado_intc NOT NULL,
  "fecha_creacion" timestamp DEFAULT (NOW()),
  "fecha_cierre" timestamp DEFAULT (NOW() + INTERVAL '30 Days'),
  "usuario_id" int NOT NULL,
  "publicacion_id" int NOT NULL
);

CREATE TABLE "Mensaje" (
  "id_mensaje" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "contenido" text NOT NULL,
  "fecha_envio" timestamp DEFAULT (NOW()),
  "emisor_id" int NOT NULL,
  "receptor_id" int NOT NULL,
  "intercambio_id" int
);

CREATE TABLE "Custodia_Creditos" (
  "id_custodia_creditos" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "monto" money NOT NULL,
  "estado" estado_intc NOT NULL,
  "fecha_retenido" timestamp DEFAULT (NOW()),
  "fecha_liberacion" timestamp DEFAULT (NOW() + INTERVAL '30 Days'),
  "comprador_id" int NOT NULL,
  "oferente_id" int NOT NULL,
  "billetera_vendedor" int NOT NULL,
  "billetera_comprador" int NOT NULL,
  "intercambio_id" int NOT NULL
);

CREATE TABLE "Equivalencia_Ecologica" (
  "id_equivalencia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "descripcion" text,
  "unidad_medida" unidades NOT NULL,
  "fecha_inicio" timestamp DEFAULT (NOW()),
  "categoria_id" int NOT NULL
);

CREATE TABLE "Factor_Equivalencia" (
  "id_factor_eq" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "co2xkg" decimal NOT NULL,
  "energiaxkwh" decimal NOT NULL,
  "aguaxlitro" decimal NOT NULL,
  "equivalencia_id" int NOT NULL
);

CREATE TABLE "Reportes_Impacto" (
  "id_reporte" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_usuario" int NOT NULL,
  "co2" decimal NOT NULL DEFAULT 0,
  "energia_ahorrada" decimal NOT NULL DEFAULT 0,
  "agua_preservada" decimal NOT NULL DEFAULT 0,
  "fecha_registro" timestamp DEFAULT (NOW()),
  "publicacion_id" int NOT NULL
);

CREATE TABLE "Acelerador_Credito" (
  "id_acelerador" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "tipo" varchar NOT NULL,
  "multiplicador" decimal NOT NULL,
  "estado" boolean NOT NULL,
  "fecha_inicio" timestamp DEFAULT (NOW()),
  "fecha_fin" timestamp,
  "billetera_id" int NOT NULL,
  "campana_id" int NOT NULL
);

CREATE TABLE "Campana_Ecologica" (
  "id_campana" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "descripcion" text,
  "tipo" tipo_campana NOT NULL,
  "estado" boolean,
  "fecha_inicio" timestamp DEFAULT (NOW()),
  "fecha_fin" timestamp NOT NULL
);

ALTER TABLE "Usuario" ADD FOREIGN KEY ("rol_id") REFERENCES "Rol" ("id_rol");

ALTER TABLE "Bitacora_Usuario" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id_usuario");

ALTER TABLE "Billetera" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id_usuario");

ALTER TABLE "Movimiento_Credito" ADD FOREIGN KEY ("billetera_id") REFERENCES "Billetera" ("id_billetera");

ALTER TABLE "Billetera_Puntos" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id_usuario");

ALTER TABLE "Publicacion" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id_usuario");

ALTER TABLE "Publicacion" ADD FOREIGN KEY ("categoria_id") REFERENCES "Categoria" ("id_categoria");

ALTER TABLE "Favorito" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id_usuario");

ALTER TABLE "Favorito" ADD FOREIGN KEY ("publicacion_id") REFERENCES "Publicacion" ("id_publicacion");

ALTER TABLE "Compra_Paquete" ADD FOREIGN KEY ("billetera_puntos_id") REFERENCES "Billetera_Puntos" ("id_billetera_Puntos");

ALTER TABLE "Compra_Paquete" ADD FOREIGN KEY ("paquete_recarga_id") REFERENCES "Paquete_Recarga" ("id_paquete");

ALTER TABLE "Canjeo_Puntos" ADD FOREIGN KEY ("billetera_id") REFERENCES "Billetera" ("id_billetera");

ALTER TABLE "Canjeo_Puntos" ADD FOREIGN KEY ("billetera_puntos_id") REFERENCES "Billetera_Puntos" ("id_billetera_Puntos");

ALTER TABLE "Intercambio" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id_usuario");

ALTER TABLE "Intercambio" ADD FOREIGN KEY ("publicacion_id") REFERENCES "Publicacion" ("id_publicacion");

ALTER TABLE "Mensaje" ADD FOREIGN KEY ("emisor_id") REFERENCES "Usuario" ("id_usuario");

ALTER TABLE "Mensaje" ADD FOREIGN KEY ("receptor_id") REFERENCES "Usuario" ("id_usuario");

ALTER TABLE "Mensaje" ADD FOREIGN KEY ("intercambio_id") REFERENCES "Intercambio" ("id_intercambio");

ALTER TABLE "Custodia_Creditos" ADD FOREIGN KEY ("billetera_comprador") REFERENCES "Billetera" ("id_billetera");

ALTER TABLE "Custodia_Creditos" ADD FOREIGN KEY ("intercambio_id") REFERENCES "Intercambio" ("id_intercambio");

ALTER TABLE "Equivalencia_Ecologica" ADD FOREIGN KEY ("categoria_id") REFERENCES "Categoria" ("id_categoria");

ALTER TABLE "Factor_Equivalencia" ADD FOREIGN KEY ("equivalencia_id") REFERENCES "Equivalencia_Ecologica" ("id_equivalencia");

ALTER TABLE "Reportes_Impacto" ADD FOREIGN KEY ("publicacion_id") REFERENCES "Publicacion" ("id_publicacion");

ALTER TABLE "Acelerador_Credito" ADD FOREIGN KEY ("billetera_id") REFERENCES "Billetera" ("id_billetera");

ALTER TABLE "Acelerador_Credito" ADD FOREIGN KEY ("campana_id") REFERENCES "Campana_Ecologica" ("id_campana");
